apiVersion: dbforpostgresql.azure.upbound.io/v1beta2
kind: FlexibleServer
metadata:
  name: flexiblesvr
spec:
  forProvider:
    administratorLogin: psqladmin
    administratorPasswordSecretRef:
      key: example-key
      name: example-secret
      namespace: crossplane-system
    autoGeneratePassword: true
    location: Central US
    publicNetworkAccessEnabled: false
    resourceGroupName: hcl-cus-rsg-d-genai
    skuName: B_Standard_B1ms  # Lower-cost burstable SKU
    storageMb: 32768   # Reduced storage
    storageTier: P4          # Lower-cost storage tier
    version: "16"
